accounts/urls.py
from django.urls import path

from .views import SignUpView

app_name = "accouonts"
urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

apis/urls.py
from django.urls import path, include

from .views import TaskListCreateAPIView, TaskUpdateDeleteView

urlpatterns = [
    path("auth/", include("djoser.urls")),
    path("auth/", include("djoser.urls.authtoken")),
    path("tasks/", TaskListCreateAPIView.as_view()),
    path("tasks/<int:pk>/", TaskUpdateDeleteView.as_view()),
]

todo_app/urls.py
from django.urls import path
from .views import (
    TaskListView,
    TaskDeleteView,
    TaskCreateView,
    TaskUpdateView,
    toggle_task_status,
    completed_tasks_delete,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task_list"),
    path("create/", TaskCreateView.as_view(), name="task_create"),
    path("update/<int:pk>/", TaskUpdateView.as_view(), name="task_update"),
    path("delete/<int:pk>/", TaskDeleteView.as_view(), name="task_delete"),
    path("toggle/<int:pk>/", toggle_task_status, name="task_toggle"),
    path(
        "delete-completed-task/", completed_tasks_delete, name="completed_tasks_delete"
    ),
]

todo_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls", namespace="auth")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("api/", include("apis.urls")),
    path("", include("todo_app.urls")),
]

accounts/models.py
from django.db import models

# Create your models here.

apis/models.py
from django.db import models

# Create your models here.

todo_app/models.py
from datetime import timedelta

from django.db import models
from django.urls import reverse
from django.utils import timezone


class Todo(models.Model):
    user = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    task = models.CharField(max_length=255)
    completed = models.BooleanField(default=False)
    due_date = models.DateField(null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.task} - {self.user.username}"

    def get_absolute_url(self):
        return reverse("task_update", kwargs={"pk": self.pk})

    class Meta:
        ordering = ["completed", "-created_at"]

    def overdue(self):
        if self.due_date:
            return timezone.now().date() > self.due_date
        return False

todo_app/forms.py
from django import forms
from .models import Todo


class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ["task", "due_date", "completed"]
        widgets = {
            "due_date": forms.DateInput(attrs={"type": "date"}),
        }

accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm


# Create your views here.
class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("auth:login")
    template_name = "registration/signup.html"

apis/views.py
from rest_framework.generics import (
    ListCreateAPIView,
    GenericAPIView,
    RetrieveUpdateDestroyAPIView,
)
from rest_framework.mixins import UpdateModelMixin, DestroyModelMixin
from rest_framework.permissions import IsAuthenticated

from .serializers import TodoSerializer
from todo_app.models import Todo


class TaskListCreateAPIView(ListCreateAPIView):
    serializer_class = TodoSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        return Todo.objects.filter(user=self.request.user)

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


"""
class TaskUpdateDeleteView(UpdateModelMixin, DestroyModelMixin, GenericAPIView):
    serializer_class = TodoSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        return Todo.objects.filter(user=self.request.user)

    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def patch(self, request, *args, **kwargs):
        return self.partial_update(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)
"""


class TaskUpdateDeleteView(RetrieveUpdateDestroyAPIView):
    serializer_class = TodoSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        return Todo.objects.filter(user=self.request.user)

todo_app/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import DeleteView, CreateView, UpdateView
from django.shortcuts import get_object_or_404, redirect

from .forms import TodoForm
from .models import Todo


class TaskListView(LoginRequiredMixin, ListView):
    model = Todo
    template_name = "task_list.html"

    def get_queryset(self):
        search = self.request.GET.get("search")
        ordering = self.request.GET.get("ordering")

        task_list = Todo.objects.filter(user=self.request.user)

        if search:
            task_list = task_list.filter(task__icontains=search)

        if ordering:
            ALLOWED_ORDERING_FIELDS = [
                "created_at",
                "-created_at",
                "due_date",
                "-due_date",
            ]
            if ordering in ALLOWED_ORDERING_FIELDS:
                task_list = task_list.order_by(ordering)

        return task_list


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Todo
    form_class = TodoForm
    template_name = "task_create.html"
    success_url = reverse_lazy("task_list")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Todo
    form_class = TodoForm
    template_name = "task_update.html"
    success_url = reverse_lazy("task_list")

    def get_queryset(self):
        return Todo.objects.filter(user=self.request.user)


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    template_name = "task_delete.html"
    success_url = reverse_lazy("task_list")

    def get_queryset(self):
        return Todo.objects.filter(user=self.request.user)


@login_required
def toggle_task_status(request, pk):
    task = get_object_or_404(Todo, pk=pk, user=request.user)
    task.completed = not task.completed
    task.save()
    return redirect("task_list")


@login_required
def completed_tasks_delete(request):
    tasks = Todo.objects.filter(user=request.user, completed=True)
    tasks.delete()
    return redirect("task_list")

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
        <title>{% block title %}Home{% endblock title %}</title>
    </head>
    <body>
        <main>
        {% if user.is_authenticated %}
            <div id="flex-end-container">
                <form method="post" action="{% url 'auth:logout' %}">
                    {% csrf_token %}
                    <button class="btn-gradient-radius" type="submit">Log Out</button>
                </form>
            </div>
        {% endif %}
        {% block content %}{% endblock content%}
        </main>
    </body>
</html>

templates/task_create.html
{% extends "base.html" %}

{% block content %}
<h2>Add Task</h2>
<form method="post" action="">
    {% csrf_token %}
    <p>{{ form.task.label }}: </p>
    {{ form.task }}
    <p>{{ form.due_date.label }}: </p>
    {{ form.due_date }}<br />
    <button class="btn-gradient-radius margin-t1" type="submit">Add Task</button>
</form>
<a href="{% url 'task_list' %}" class="margin-t1">Back</a><br />
{% endblock content %}

templates/task_delete.html
{% extends "base.html" %}

{% block title %}Delete Task{% endblock title %}

{% block content %}
<h2>Delete Task</h2>
<form method="post">
    {% csrf_token %}
    <p>Are your sure you want to delete this task? "{{ object.task }}"</p>
    <button type="submit" class="btn-gradient-radius">Delete</button>
</form>
<a href="{% url 'task_list' %}" class="margin-t1">Back</a><br />
{% endblock content %}

templates/task_list.html
{% extends 'base.html'%}

{% block title %}Task List{% endblock title%}

{% block content %}
<h2>Task List</h2>
<div id="flex-end-container" class="margin-b1">
    <a href="{% url 'task_create' %}"><button class="btn-gradient-radius">Add Task</button></a>
    <br />
</div>
<form method="get" class="margin-b1">
    {% csrf_token %}
    <input type="text" name="search" placeholder="Search tasks..." value="{{ request.GET.search }}">
    <select name="ordering">
        <option value="">Ordering</option>
        <option value="created_at" {% if request.GET.ordering == "created_at" %}selected{% endif %}>Create Date(Asc)</option>
        <option value="-created_at" {% if request.GET.ordering == "-created_at" %}selected{% endif %}>Create Date(Desc)</option>
        <option value="due_date" {% if request.GET.ordering == "due_date" %}selected{% endif %}>Due Date(Asc)</option>
        <option value="-due_date" {% if request.GET.ordering == "-due_date" %}selected{% endif %}>Due Date(Desc)</option>
    </select>
    <button class="btn-gradient-radius" type="submit">Search & Sort</button>
</form>
{% for task in todo_list %}
<div class="task-container">
    <label class="task">
        <input type="checkbox" {% if task.completed %}checked{% endif %} disabled>
        {% if task.completed %}
            <del><span>{{ task.task }}</span></del>
        {% else %}
            {% if task.overdue %}<strong class="color-red">{% endif %}<span>{{ task.task }}</span>{% if task.overdue %}</strong>{% endif %}
        {% endif %}
        <small>
            {% if task.due_date %}
            {{ task.due_date|date:"- m/d" }}
            {% endif %}
        </small>
    </label>
    <form method="post" action="{% url 'task_toggle' task.pk %}">
      {% csrf_token %}
      <button class="btn-gradient-radius" type="submit">
        {% if task.completed %}Incomplete{% else %}Complete{% endif %}
      </button>
    </form>
    <a href="{% url 'task_update' task.id %}"><button class="btn-gradient-radius">Edit</button></a>
    <a href="{% url 'task_delete' task.id %}"><button class="btn-gradient-radius">Delete</button></a>
</div>
{% endfor %}
<form method="post" action="{% url 'completed_tasks_delete' %}">
    {% csrf_token %}
    <button type="submit" class="margin-t1 btn-gradient-radius">Delete Completed Tasks</button>
</form>
{% if request.GET.search %}
<p class="margin-t1"><a href="{% url 'task_list' %}">Back to Task List</a></p>
{% endif %}
{% endblock content %}

templates/task_update.html
{% extends "base.html" %}

{% block content %}
<h2>Update Task</h2>
<form method="post" action="">
    {% csrf_token %}
    <p>{{ form.task.label }}: </p>
    {{ form.task }}
    <p>{{ form.due_date.label }}: </p>
    {{ form.due_date }}
    <p>{{ form.completed.label }}:</p>
    {{ form.completed}}<br />
    <button type="submit" class="btn-gradient-radius margin-t1">Update Task</button>
</form>
<a href="{% url 'task_list' %}" class="margin-t1">Back</a><br />
{% endblock content %}